version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "5000:80"

  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: symfony
    ports:
      - "5433:5432"
